# Test credentials for CI and local test runs
# These are not sensitive and can be committed to the repository

# JWT secret for devise-jwt authentication
devise_jwt_secret_key: test_jwt_secret_key_for_testing_only_not_for_production_use_1234567890abcdef

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: test_secret_key_base_for_testing_only_not_for_production_use_1234567890abcdef