plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - "bin/**/*"
    - "bin/{bundle,rails,rake,setup}"
    - "db/schema.rb"
    - "db/migrate/*"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "scripts/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/LineLength:
  Max: 135
  AutoCorrect: true
  Exclude:
    - "config/**/*"
    - "test/**/*"

Lint/SuppressedException:
  Exclude:
    - "test/**/*"

# Disable all Metrics cops - we don't use them
Metrics:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  SingleLineConditionsOnly: false
  IncludeTernaryExpressions: false

Style/FormatString:
  EnforcedStyle: percent
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

# I don't mind this being enabled if
# someone fixes all the fails.
Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/Blank:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/RefuteMethods:
  EnforcedStyle: refute

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false