AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Jiki Video Production Lambda Functions

Globals:
  Function:
    Timeout: 900  # 15 minutes
    MemorySize: 3008  # Maximum memory for better CPU allocation
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        AWS_REGION: !Ref AWS::Region
        NODE_OPTIONS: --enable-source-maps

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  S3BucketName:
    Type: String
    Description: S3 bucket name for video storage
    Default: jiki-videos-dev

Resources:
  # Video Merger Lambda Function
  VideoMergerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub jiki-video-merger-${Environment}
      CodeUri: video-merger/
      Handler: dist/index.handler
      Description: Merges multiple video files using FFmpeg
      EphemeralStorage:
        Size: 10240  # 10 GB for large video files
      Layers:
        # FFmpeg layer - update this ARN based on your region
        # See: https://github.com/serverlesspub/ffmpeg-aws-lambda-layer
        - arn:aws:lambda:us-east-1:145266761615:layer:ffmpeg:4
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
        - S3WritePolicy:
            BucketName: !Ref S3BucketName
      Tags:
        Project: jiki
        Component: video-production
        Environment: !Ref Environment

  # CloudWatch Log Group (with retention)
  VideoMergerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VideoMergerFunction}
      RetentionInDays: 14

Outputs:
  VideoMergerFunctionArn:
    Description: ARN of the Video Merger Lambda function
    Value: !GetAtt VideoMergerFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VideoMergerFunctionArn

  VideoMergerFunctionName:
    Description: Name of the Video Merger Lambda function
    Value: !Ref VideoMergerFunction
    Export:
      Name: !Sub ${AWS::StackName}-VideoMergerFunctionName
